name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # This is required to access your Dockerfiles

      - name: Build Frontend
        uses: docker/build-push-action@v6
        with:
          context: ./client
          file: ./client/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: plantio1/frontend:latest

      - name: Build Product Service
        uses: docker/build-push-action@v6
        with:
          context: ./product-service
          file: ./product-service/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: plantio1/product-service:latest

      - name: Build API Gateway
        uses: docker/build-push-action@v6
        with:
          context: ./api-gateway
          file: ./api-gateway/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: plantio1/api-gateway:latest

      - name: Build Discovery Service
        uses: docker/build-push-action@v6
        with:
          context: ./discovery-service
          file: ./discovery-service/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: plantio1/discovery-service:latest