name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # List every folder that needs a Docker image
        include:
          - service: frontend
            image: frontend
            is_maven: false
          - service: products-service
            image: product-service
            is_maven: true
          - service: api-gateway
            image: api-gateway
            is_maven: true
          - service: discovery-server
            image: discovery-server
            is_maven: true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Only setup Java if the current matrix service is Maven-based
      - name: Set up JDK 21
        if: ${{ matrix.is_maven == true }}
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Only run Maven if the folder has a pom.xml
      - name: Build with Maven
        if: ${{ matrix.is_maven == true }}
        run: mvn clean package -DskipTests -f ${{ matrix.service }}/pom.xml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: plantio1/${{ matrix.image }}:latest
